# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pyRoastUI.ui'
#
# Created: Wed Jun 26 18:26:11 2013
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1078, 765)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.layoutWidget = QtGui.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(890, 40, 145, 364))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_6 = QtGui.QLabel(self.layoutWidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout.addWidget(self.label_6)
        self.tCurrentTemperature_2 = QtGui.QLabel(self.layoutWidget)
        self.tCurrentTemperature_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tCurrentTemperature_2.setObjectName(_fromUtf8("tCurrentTemperature_2"))
        self.horizontalLayout.addWidget(self.tCurrentTemperature_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_4 = QtGui.QLabel(self.layoutWidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_2.addWidget(self.label_4)
        self.tMaxTemperature = QtGui.QLabel(self.layoutWidget)
        self.tMaxTemperature.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tMaxTemperature.setObjectName(_fromUtf8("tMaxTemperature"))
        self.horizontalLayout_2.addWidget(self.tMaxTemperature)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label = QtGui.QLabel(self.layoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_3.addWidget(self.label)
        self.tRateOfChange = QtGui.QLabel(self.layoutWidget)
        self.tRateOfChange.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tRateOfChange.setObjectName(_fromUtf8("tRateOfChange"))
        self.horizontalLayout_3.addWidget(self.tRateOfChange)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.label_5 = QtGui.QLabel(self.layoutWidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout.addWidget(self.label_5)
        self.bFirstCrack = KPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.bFirstCrack.sizePolicy().hasHeightForWidth())
        self.bFirstCrack.setSizePolicy(sizePolicy)
        self.bFirstCrack.setObjectName(_fromUtf8("bFirstCrack"))
        self.verticalLayout.addWidget(self.bFirstCrack)
        self.bRollingFirstCrack = KPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.bRollingFirstCrack.sizePolicy().hasHeightForWidth())
        self.bRollingFirstCrack.setSizePolicy(sizePolicy)
        self.bRollingFirstCrack.setObjectName(_fromUtf8("bRollingFirstCrack"))
        self.verticalLayout.addWidget(self.bRollingFirstCrack)
        self.bSecondCrack = KPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.bSecondCrack.sizePolicy().hasHeightForWidth())
        self.bSecondCrack.setSizePolicy(sizePolicy)
        self.bSecondCrack.setObjectName(_fromUtf8("bSecondCrack"))
        self.verticalLayout.addWidget(self.bSecondCrack)
        self.bRollingSecondCrack = KPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.bRollingSecondCrack.sizePolicy().hasHeightForWidth())
        self.bRollingSecondCrack.setSizePolicy(sizePolicy)
        self.bRollingSecondCrack.setObjectName(_fromUtf8("bRollingSecondCrack"))
        self.verticalLayout.addWidget(self.bRollingSecondCrack)
        self.bReset = KPushButton(self.layoutWidget)
        self.bReset.setObjectName(_fromUtf8("bReset"))
        self.verticalLayout.addWidget(self.bReset)
        self.TemperaturePlot = KPlotWidget(self.centralwidget)
        self.TemperaturePlot.setGeometry(QtCore.QRect(20, 10, 831, 411))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.TemperaturePlot.sizePolicy().hasHeightForWidth())
        self.TemperaturePlot.setSizePolicy(sizePolicy)
        self.TemperaturePlot.setMinimumSize(QtCore.QSize(600, 300))
        self.TemperaturePlot.setMaximumSize(QtCore.QSize(2000, 2000))
        self.TemperaturePlot.setSizeIncrement(QtCore.QSize(1, 1))
        self.TemperaturePlot.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.TemperaturePlot.setFont(font)
        self.TemperaturePlot.setProperty("backgroundColor", QtGui.QColor(0, 0, 0))
        self.TemperaturePlot.setObjectName(_fromUtf8("TemperaturePlot"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 449, 590, 271))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(590, 270))
        self.groupBox.setMaximumSize(QtCore.QSize(931, 300))
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setFlat(True)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.bSave = KPushButton(self.groupBox)
        self.bSave.setGeometry(QtCore.QRect(10, 230, 75, 32))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bSave.sizePolicy().hasHeightForWidth())
        self.bSave.setSizePolicy(sizePolicy)
        self.bSave.setObjectName(_fromUtf8("bSave"))
        self.bSaveAs = KPushButton(self.groupBox)
        self.bSaveAs.setGeometry(QtCore.QRect(100, 230, 75, 32))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bSaveAs.sizePolicy().hasHeightForWidth())
        self.bSaveAs.setSizePolicy(sizePolicy)
        self.bSaveAs.setObjectName(_fromUtf8("bSaveAs"))
        self.bQuit = KPushButton(self.groupBox)
        self.bQuit.setGeometry(QtCore.QRect(190, 230, 71, 32))
        self.bQuit.setObjectName(_fromUtf8("bQuit"))
        self.widget = QtGui.QWidget(self.groupBox)
        self.widget.setGeometry(QtCore.QRect(290, 20, 258, 201))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_2 = QtGui.QLabel(self.widget)
        self.label_2.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setKerning(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_4.addWidget(self.label_2)
        self.comboBox = QtGui.QComboBox(self.widget)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.horizontalLayout_4.addWidget(self.comboBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.label_10 = QtGui.QLabel(self.widget)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.verticalLayout_3.addWidget(self.label_10)
        self.notes_2 = QtGui.QTextEdit(self.widget)
        self.notes_2.setObjectName(_fromUtf8("notes_2"))
        self.verticalLayout_3.addWidget(self.notes_2)
        self.widget1 = QtGui.QWidget(self.groupBox)
        self.widget1.setGeometry(QtCore.QRect(10, 20, 258, 191))
        self.widget1.setObjectName(_fromUtf8("widget1"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.widget1)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_8 = QtGui.QLabel(self.widget1)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout_4.addWidget(self.label_8)
        self.coffee = QtGui.QLineEdit(self.widget1)
        self.coffee.setObjectName(_fromUtf8("coffee"))
        self.verticalLayout_4.addWidget(self.coffee)
        self.label_9 = QtGui.QLabel(self.widget1)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout_4.addWidget(self.label_9)
        self.notes = QtGui.QTextEdit(self.widget1)
        self.notes.setObjectName(_fromUtf8("notes"))
        self.verticalLayout_4.addWidget(self.notes)
        self.CSLogo = QtGui.QLabel(self.centralwidget)
        self.CSLogo.setGeometry(QtCore.QRect(780, 430, 86, 270))
        self.CSLogo.setMaximumSize(QtCore.QSize(171, 16777215))
        self.CSLogo.setObjectName(_fromUtf8("CSLogo"))
        self.tMessages = KTextBrowser(self.centralwidget)
        self.tMessages.setGeometry(QtCore.QRect(890, 450, 161, 231))
        self.tMessages.setObjectName(_fromUtf8("tMessages"))
        self.widget2 = QtGui.QWidget(self.centralwidget)
        self.widget2.setGeometry(QtCore.QRect(630, 460, 116, 221))
        self.widget2.setObjectName(_fromUtf8("widget2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.widget2)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.cAutoPower = QtGui.QCheckBox(self.widget2)
        self.cAutoPower.setObjectName(_fromUtf8("cAutoPower"))
        self.verticalLayout_2.addWidget(self.cAutoPower)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_7 = QtGui.QLabel(self.widget2)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_5.addWidget(self.label_7)
        self.vTarget = QtGui.QDoubleSpinBox(self.widget2)
        self.vTarget.setDecimals(1)
        self.vTarget.setMaximum(400.0)
        self.vTarget.setSingleStep(0.1)
        self.vTarget.setObjectName(_fromUtf8("vTarget"))
        self.horizontalLayout_5.addWidget(self.vTarget)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.tPower = QtGui.QLabel(self.widget2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tPower.sizePolicy().hasHeightForWidth())
        self.tPower.setSizePolicy(sizePolicy)
        self.tPower.setMinimumSize(QtCore.QSize(70, 0))
        self.tPower.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tPower.setObjectName(_fromUtf8("tPower"))
        self.verticalLayout_2.addWidget(self.tPower)
        self.sPowerSlider = QtGui.QSlider(self.widget2)
        self.sPowerSlider.setOrientation(QtCore.Qt.Vertical)
        self.sPowerSlider.setObjectName(_fromUtf8("sPowerSlider"))
        self.verticalLayout_2.addWidget(self.sPowerSlider)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1078, 19))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label_6.setText(_translate("MainWindow", "Temperature:", None))
        self.tCurrentTemperature_2.setText(_translate("MainWindow", "0.0", None))
        self.label_4.setText(_translate("MainWindow", "Max Temperature:", None))
        self.tMaxTemperature.setText(_translate("MainWindow", "0.0", None))
        self.label.setText(_translate("MainWindow", "Rate of Change:", None))
        self.tRateOfChange.setText(_translate("MainWindow", "0.0", None))
        self.label_5.setText(_translate("MainWindow", "Elapsed Time:", None))
        self.bFirstCrack.setText(_translate("MainWindow", "First\n"
"Crack", None))
        self.bRollingFirstCrack.setText(_translate("MainWindow", "Rolling\n"
"First Crack", None))
        self.bSecondCrack.setText(_translate("MainWindow", "Second\n"
"Crack", None))
        self.bRollingSecondCrack.setText(_translate("MainWindow", "Rolling\n"
"Second Crack", None))
        self.bReset.setText(_translate("MainWindow", "Reset", None))
        self.bSave.setText(_translate("MainWindow", "Save", None))
        self.bSaveAs.setText(_translate("MainWindow", "Save As", None))
        self.bQuit.setText(_translate("MainWindow", "Quit", None))
        self.label_2.setText(_translate("MainWindow", "File Name:", None))
        self.label_10.setText(_translate("MainWindow", "Roast Notes:", None))
        self.label_8.setText(_translate("MainWindow", "Coffee:", None))
        self.label_9.setText(_translate("MainWindow", "Roast Notes:", None))
        self.CSLogo.setText(_translate("MainWindow", "Thanks to\n"
"CoffeeSnobs!", None))
        self.cAutoPower.setText(_translate("MainWindow", "Auto Power", None))
        self.label_7.setText(_translate("MainWindow", "Target:", None))
        self.tPower.setText(_translate("MainWindow", "100%", None))

from PyKDE4.kdeui import KPushButton, KPlotWidget, KTextBrowser
