# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pyRoastUI.ui'
#
# Created: Sun Jul  7 16:03:10 2013
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_pyRoast(object):
    def setupUi(self, pyRoast):
        pyRoast.setObjectName(_fromUtf8("pyRoast"))
        pyRoast.resize(823, 627)
        self.centralwidget = QtGui.QWidget(pyRoast)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_18 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout_4.addWidget(self.label_8)
        self.coffee = QtGui.QLineEdit(self.centralwidget)
        self.coffee.setObjectName(_fromUtf8("coffee"))
        self.verticalLayout_4.addWidget(self.coffee)
        self.label_9 = QtGui.QLabel(self.centralwidget)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout_4.addWidget(self.label_9)
        self.notes = QtGui.QTextEdit(self.centralwidget)
        self.notes.setMinimumSize(QtCore.QSize(200, 0))
        self.notes.setObjectName(_fromUtf8("notes"))
        self.verticalLayout_4.addWidget(self.notes)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.bSave = QtGui.QPushButton(self.centralwidget)
        self.bSave.setObjectName(_fromUtf8("bSave"))
        self.horizontalLayout_7.addWidget(self.bSave)
        self.bSaveAs = QtGui.QPushButton(self.centralwidget)
        self.bSaveAs.setObjectName(_fromUtf8("bSaveAs"))
        self.horizontalLayout_7.addWidget(self.bSaveAs)
        self.bQuit = QtGui.QPushButton(self.centralwidget)
        self.bQuit.setObjectName(_fromUtf8("bQuit"))
        self.horizontalLayout_7.addWidget(self.bQuit)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8.addLayout(self.verticalLayout_4)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_11 = QtGui.QLabel(self.centralwidget)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.verticalLayout_3.addWidget(self.label_11)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setKerning(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_4.addWidget(self.label_2)
        self.comboBox = QtGui.QComboBox(self.centralwidget)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.horizontalLayout_4.addWidget(self.comboBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.label_10 = QtGui.QLabel(self.centralwidget)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.verticalLayout_3.addWidget(self.label_10)
        self.notes_2 = QtGui.QTextEdit(self.centralwidget)
        self.notes_2.setMinimumSize(QtCore.QSize(200, 0))
        self.notes_2.setObjectName(_fromUtf8("notes_2"))
        self.verticalLayout_3.addWidget(self.notes_2)
        self.horizontalLayout_8.addLayout(self.verticalLayout_3)
        self.gridLayout.addLayout(self.horizontalLayout_8, 1, 0, 1, 1)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.cAutoPower = QtGui.QCheckBox(self.centralwidget)
        self.cAutoPower.setMaximumSize(QtCore.QSize(100, 16777215))
        self.cAutoPower.setObjectName(_fromUtf8("cAutoPower"))
        self.verticalLayout_2.addWidget(self.cAutoPower)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_5.addWidget(self.label_7)
        self.vTarget = QtGui.QDoubleSpinBox(self.centralwidget)
        self.vTarget.setMaximumSize(QtCore.QSize(50, 16777215))
        self.vTarget.setDecimals(1)
        self.vTarget.setMaximum(400.0)
        self.vTarget.setSingleStep(0.1)
        self.vTarget.setObjectName(_fromUtf8("vTarget"))
        self.horizontalLayout_5.addWidget(self.vTarget)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.sPowerSlider = QtGui.QSlider(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sPowerSlider.sizePolicy().hasHeightForWidth())
        self.sPowerSlider.setSizePolicy(sizePolicy)
        self.sPowerSlider.setMaximumSize(QtCore.QSize(50, 300))
        self.sPowerSlider.setBaseSize(QtCore.QSize(0, 0))
        self.sPowerSlider.setMaximum(100)
        self.sPowerSlider.setOrientation(QtCore.Qt.Vertical)
        self.sPowerSlider.setObjectName(_fromUtf8("sPowerSlider"))
        self.horizontalLayout_9.addWidget(self.sPowerSlider)
        self.tPower = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tPower.sizePolicy().hasHeightForWidth())
        self.tPower.setSizePolicy(sizePolicy)
        self.tPower.setMinimumSize(QtCore.QSize(40, 0))
        self.tPower.setMaximumSize(QtCore.QSize(50, 16777215))
        self.tPower.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tPower.setObjectName(_fromUtf8("tPower"))
        self.horizontalLayout_9.addWidget(self.tPower)
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_9.addWidget(self.label)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.gridLayout.addLayout(self.verticalLayout_2, 1, 1, 1, 1)
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.CSLogo = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CSLogo.sizePolicy().hasHeightForWidth())
        self.CSLogo.setSizePolicy(sizePolicy)
        self.CSLogo.setMinimumSize(QtCore.QSize(100, 0))
        self.CSLogo.setMaximumSize(QtCore.QSize(171, 16777215))
        self.CSLogo.setObjectName(_fromUtf8("CSLogo"))
        self.verticalLayout_11.addWidget(self.CSLogo)
        self.tMessages = QtGui.QTextBrowser(self.centralwidget)
        self.tMessages.setObjectName(_fromUtf8("tMessages"))
        self.verticalLayout_11.addWidget(self.tMessages)
        self.gridLayout.addLayout(self.verticalLayout_11, 1, 2, 1, 1)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.label_15 = QtGui.QLabel(self.centralwidget)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_14.addWidget(self.label_15)
        self.tCurrentTemperature = QtGui.QLabel(self.centralwidget)
        self.tCurrentTemperature.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tCurrentTemperature.setObjectName(_fromUtf8("tCurrentTemperature"))
        self.horizontalLayout_14.addWidget(self.tCurrentTemperature)
        self.verticalLayout_6.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.label_16 = QtGui.QLabel(self.centralwidget)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_15.addWidget(self.label_16)
        self.tMaxTemperature = QtGui.QLabel(self.centralwidget)
        self.tMaxTemperature.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tMaxTemperature.setObjectName(_fromUtf8("tMaxTemperature"))
        self.horizontalLayout_15.addWidget(self.tMaxTemperature)
        self.verticalLayout_6.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.label_17 = QtGui.QLabel(self.centralwidget)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_16.addWidget(self.label_17)
        self.tRateOfChange = QtGui.QLabel(self.centralwidget)
        self.tRateOfChange.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tRateOfChange.setObjectName(_fromUtf8("tRateOfChange"))
        self.horizontalLayout_16.addWidget(self.tRateOfChange)
        self.verticalLayout_6.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.label_18 = QtGui.QLabel(self.centralwidget)
        self.label_18.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.horizontalLayout_17.addWidget(self.label_18)
        self.tElapsed = QtGui.QLabel(self.centralwidget)
        self.tElapsed.setMaximumSize(QtCore.QSize(16777215, 30))
        self.tElapsed.setText(_fromUtf8(""))
        self.tElapsed.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tElapsed.setObjectName(_fromUtf8("tElapsed"))
        self.horizontalLayout_17.addWidget(self.tElapsed)
        self.verticalLayout_6.addLayout(self.horizontalLayout_17)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem)
        self.bFirstCrack = QtGui.QPushButton(self.centralwidget)
        self.bFirstCrack.setObjectName(_fromUtf8("bFirstCrack"))
        self.verticalLayout_6.addWidget(self.bFirstCrack)
        self.bRollingFirstCrack = QtGui.QPushButton(self.centralwidget)
        self.bRollingFirstCrack.setObjectName(_fromUtf8("bRollingFirstCrack"))
        self.verticalLayout_6.addWidget(self.bRollingFirstCrack)
        self.bSecondCrack = QtGui.QPushButton(self.centralwidget)
        self.bSecondCrack.setObjectName(_fromUtf8("bSecondCrack"))
        self.verticalLayout_6.addWidget(self.bSecondCrack)
        self.bRollingSecondCrack = QtGui.QPushButton(self.centralwidget)
        self.bRollingSecondCrack.setObjectName(_fromUtf8("bRollingSecondCrack"))
        self.verticalLayout_6.addWidget(self.bRollingSecondCrack)
        self.bReset = QtGui.QPushButton(self.centralwidget)
        self.bReset.setObjectName(_fromUtf8("bReset"))
        self.verticalLayout_6.addWidget(self.bReset)
        self.gridLayout.addLayout(self.verticalLayout_6, 0, 2, 1, 1)
        self.TemperaturePlot = KPlotWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.TemperaturePlot.sizePolicy().hasHeightForWidth())
        self.TemperaturePlot.setSizePolicy(sizePolicy)
        self.TemperaturePlot.setMinimumSize(QtCore.QSize(600, 400))
        self.TemperaturePlot.setMaximumSize(QtCore.QSize(2000, 2000))
        self.TemperaturePlot.setSizeIncrement(QtCore.QSize(1, 1))
        self.TemperaturePlot.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.TemperaturePlot.setFont(font)
        self.TemperaturePlot.setProperty("backgroundColor", QtGui.QColor(0, 0, 0))
        self.TemperaturePlot.setObjectName(_fromUtf8("TemperaturePlot"))
        self.gridLayout.addWidget(self.TemperaturePlot, 0, 0, 1, 2)
        self.horizontalLayout_18.addLayout(self.gridLayout)
        pyRoast.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(pyRoast)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 823, 19))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        pyRoast.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(pyRoast)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        pyRoast.setStatusBar(self.statusbar)

        self.retranslateUi(pyRoast)
        QtCore.QObject.connect(self.sPowerSlider, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.tPower.setNum)
        QtCore.QObject.connect(self.vTarget, QtCore.SIGNAL(_fromUtf8("valueChanged(double)")), self.tPower.setNum)
        QtCore.QMetaObject.connectSlotsByName(pyRoast)

    def retranslateUi(self, pyRoast):
        pyRoast.setWindowTitle(_translate("pyRoast", "MainWindow", None))
        self.label_8.setText(_translate("pyRoast", "Coffee:", None))
        self.label_9.setText(_translate("pyRoast", "Roast Notes:", None))
        self.bSave.setText(_translate("pyRoast", "Save", None))
        self.bSaveAs.setText(_translate("pyRoast", "Save As", None))
        self.bQuit.setText(_translate("pyRoast", "Quit", None))
        self.label_11.setText(_translate("pyRoast", "Load Roast", None))
        self.label_2.setText(_translate("pyRoast", "File Name:", None))
        self.label_10.setText(_translate("pyRoast", "Roast Notes:", None))
        self.cAutoPower.setText(_translate("pyRoast", "Auto Power", None))
        self.label_7.setText(_translate("pyRoast", "Target:", None))
        self.tPower.setText(_translate("pyRoast", "0", None))
        self.label.setText(_translate("pyRoast", "%", None))
        self.CSLogo.setText(_translate("pyRoast", "Thanks to\n"
"CoffeeSnobs!", None))
        self.label_15.setText(_translate("pyRoast", "Temperature:", None))
        self.tCurrentTemperature.setText(_translate("pyRoast", "0.0", None))
        self.label_16.setText(_translate("pyRoast", "Max Temperature:", None))
        self.tMaxTemperature.setText(_translate("pyRoast", "0.0", None))
        self.label_17.setText(_translate("pyRoast", "Rate of Change:", None))
        self.tRateOfChange.setText(_translate("pyRoast", "0.0", None))
        self.label_18.setText(_translate("pyRoast", "Elapsed Time:", None))
        self.bFirstCrack.setText(_translate("pyRoast", "First Crack", None))
        self.bRollingFirstCrack.setText(_translate("pyRoast", "Rolling First Crack", None))
        self.bSecondCrack.setText(_translate("pyRoast", "Second Crack", None))
        self.bRollingSecondCrack.setText(_translate("pyRoast", "Rolling Second Crack", None))
        self.bReset.setText(_translate("pyRoast", "Reset", None))

from PyKDE4.kdeui import KPlotWidget
