# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pyRoastUI.ui'
#
# Created: Sun Jun 23 19:05:15 2013
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_pyRoast(object):
    def setupUi(self, pyRoast):
        pyRoast.setObjectName(_fromUtf8("pyRoast"))
        pyRoast.resize(1024, 793)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(pyRoast.sizePolicy().hasHeightForWidth())
        pyRoast.setSizePolicy(sizePolicy)
        pyRoast.setMaximumSize(QtCore.QSize(3000, 3000))
        self.centralwidget = QtGui.QWidget(pyRoast)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(590, 270))
        self.groupBox.setMaximumSize(QtCore.QSize(931, 300))
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setFlat(True)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.layoutWidget = QtGui.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 170, 461, 51))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_3.addWidget(self.label_2)
        self.tFileName = KLineEdit(self.layoutWidget)
        self.tFileName.setObjectName(_fromUtf8("tFileName"))
        self.horizontalLayout_3.addWidget(self.tFileName)
        self.layoutWidget1 = QtGui.QWidget(self.groupBox)
        self.layoutWidget1.setGeometry(QtCore.QRect(0, 100, 581, 74))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.bFirstCrack = KPushButton(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.bFirstCrack.sizePolicy().hasHeightForWidth())
        self.bFirstCrack.setSizePolicy(sizePolicy)
        self.bFirstCrack.setObjectName(_fromUtf8("bFirstCrack"))
        self.horizontalLayout.addWidget(self.bFirstCrack)
        self.bRollingFirstCrack = KPushButton(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.bRollingFirstCrack.sizePolicy().hasHeightForWidth())
        self.bRollingFirstCrack.setSizePolicy(sizePolicy)
        self.bRollingFirstCrack.setObjectName(_fromUtf8("bRollingFirstCrack"))
        self.horizontalLayout.addWidget(self.bRollingFirstCrack)
        self.bSecondCrack = KPushButton(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.bSecondCrack.sizePolicy().hasHeightForWidth())
        self.bSecondCrack.setSizePolicy(sizePolicy)
        self.bSecondCrack.setObjectName(_fromUtf8("bSecondCrack"))
        self.horizontalLayout.addWidget(self.bSecondCrack)
        self.bRollingSecondCrack = KPushButton(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.bRollingSecondCrack.sizePolicy().hasHeightForWidth())
        self.bRollingSecondCrack.setSizePolicy(sizePolicy)
        self.bRollingSecondCrack.setObjectName(_fromUtf8("bRollingSecondCrack"))
        self.horizontalLayout.addWidget(self.bRollingSecondCrack)
        self.bUnload = KPushButton(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.bUnload.sizePolicy().hasHeightForWidth())
        self.bUnload.setSizePolicy(sizePolicy)
        self.bUnload.setMinimumSize(QtCore.QSize(0, 44))
        self.bUnload.setObjectName(_fromUtf8("bUnload"))
        self.horizontalLayout.addWidget(self.bUnload)
        self.layoutWidget2 = QtGui.QWidget(self.groupBox)
        self.layoutWidget2.setGeometry(QtCore.QRect(0, 232, 571, 20))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.formLayout_2 = QtGui.QFormLayout(self.layoutWidget2)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setMargin(0)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.bReset = KPushButton(self.groupBox)
        self.bReset.setGeometry(QtCore.QRect(0, 230, 75, 32))
        self.bReset.setObjectName(_fromUtf8("bReset"))
        self.bSave = KPushButton(self.groupBox)
        self.bSave.setGeometry(QtCore.QRect(80, 230, 75, 32))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bSave.sizePolicy().hasHeightForWidth())
        self.bSave.setSizePolicy(sizePolicy)
        self.bSave.setObjectName(_fromUtf8("bSave"))
        self.bSaveAs = KPushButton(self.groupBox)
        self.bSaveAs.setGeometry(QtCore.QRect(160, 230, 75, 32))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bSaveAs.sizePolicy().hasHeightForWidth())
        self.bSaveAs.setSizePolicy(sizePolicy)
        self.bSaveAs.setObjectName(_fromUtf8("bSaveAs"))
        self.bLoadProfile = KPushButton(self.groupBox)
        self.bLoadProfile.setGeometry(QtCore.QRect(240, 230, 106, 32))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bLoadProfile.sizePolicy().hasHeightForWidth())
        self.bLoadProfile.setSizePolicy(sizePolicy)
        self.bLoadProfile.setMinimumSize(QtCore.QSize(106, 0))
        self.bLoadProfile.setObjectName(_fromUtf8("bLoadProfile"))
        self.bQuit = KPushButton(self.groupBox)
        self.bQuit.setGeometry(QtCore.QRect(350, 230, 71, 32))
        self.bQuit.setObjectName(_fromUtf8("bQuit"))
        self.layoutWidget3 = QtGui.QWidget(self.groupBox)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 60, 581, 31))
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.cAutoPower = QtGui.QCheckBox(self.layoutWidget3)
        self.cAutoPower.setObjectName(_fromUtf8("cAutoPower"))
        self.horizontalLayout_2.addWidget(self.cAutoPower)
        self.tPower = QtGui.QLabel(self.layoutWidget3)
        self.tPower.setMinimumSize(QtCore.QSize(70, 0))
        self.tPower.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tPower.setObjectName(_fromUtf8("tPower"))
        self.horizontalLayout_2.addWidget(self.tPower)
        self.sPowerSlider = QtGui.QSlider(self.layoutWidget3)
        self.sPowerSlider.setToolTip(_fromUtf8(""))
        self.sPowerSlider.setMaximum(100)
        self.sPowerSlider.setPageStep(10)
        self.sPowerSlider.setProperty("value", 0)
        self.sPowerSlider.setOrientation(QtCore.Qt.Horizontal)
        self.sPowerSlider.setObjectName(_fromUtf8("sPowerSlider"))
        self.horizontalLayout_2.addWidget(self.sPowerSlider)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 0, 111, 22))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 30, 149, 22))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.tRateOfChange = QtGui.QLabel(self.groupBox)
        self.tRateOfChange.setGeometry(QtCore.QRect(470, 10, 91, 22))
        self.tRateOfChange.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tRateOfChange.setObjectName(_fromUtf8("tRateOfChange"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(290, 10, 133, 22))
        self.label.setObjectName(_fromUtf8("label"))
        self.tElapsed = QtGui.QLabel(self.groupBox)
        self.tElapsed.setGeometry(QtCore.QRect(510, 30, 51, 20))
        self.tElapsed.setText(_fromUtf8(""))
        self.tElapsed.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tElapsed.setObjectName(_fromUtf8("tElapsed"))
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(290, 30, 115, 22))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.tMaxTemperature = QtGui.QLabel(self.groupBox)
        self.tMaxTemperature.setGeometry(QtCore.QRect(175, 30, 71, 22))
        self.tMaxTemperature.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tMaxTemperature.setObjectName(_fromUtf8("tMaxTemperature"))
        self.tCurrentTemperature = QtGui.QLabel(self.groupBox)
        self.tCurrentTemperature.setGeometry(QtCore.QRect(167, 7, 81, 22))
        self.tCurrentTemperature.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tCurrentTemperature.setObjectName(_fromUtf8("tCurrentTemperature"))
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(470, 170, 41, 49))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.vTarget = QtGui.QDoubleSpinBox(self.groupBox)
        self.vTarget.setGeometry(QtCore.QRect(520, 180, 62, 28))
        self.vTarget.setDecimals(1)
        self.vTarget.setMaximum(400.0)
        self.vTarget.setSingleStep(0.1)
        self.vTarget.setObjectName(_fromUtf8("vTarget"))
        self.gridLayout.addWidget(self.groupBox, 1, 0, 1, 1)
        self.tMessages = KTextBrowser(self.centralwidget)
        self.tMessages.setObjectName(_fromUtf8("tMessages"))
        self.gridLayout.addWidget(self.tMessages, 1, 2, 1, 1)
        self.TemperaturePlot = KPlotWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.TemperaturePlot.sizePolicy().hasHeightForWidth())
        self.TemperaturePlot.setSizePolicy(sizePolicy)
        self.TemperaturePlot.setMinimumSize(QtCore.QSize(600, 300))
        self.TemperaturePlot.setMaximumSize(QtCore.QSize(2000, 2000))
        self.TemperaturePlot.setSizeIncrement(QtCore.QSize(1, 1))
        self.TemperaturePlot.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.TemperaturePlot.setFont(font)
        self.TemperaturePlot.setProperty("backgroundColor", QtGui.QColor(0, 0, 0))
        self.TemperaturePlot.setObjectName(_fromUtf8("TemperaturePlot"))
        self.gridLayout.addWidget(self.TemperaturePlot, 0, 0, 1, 2)
        self.CSLogo = QtGui.QLabel(self.centralwidget)
        self.CSLogo.setMaximumSize(QtCore.QSize(171, 16777215))
        self.CSLogo.setObjectName(_fromUtf8("CSLogo"))
        self.gridLayout.addWidget(self.CSLogo, 1, 1, 1, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout.addWidget(self.label_7)
        self.coffee = QtGui.QLineEdit(self.centralwidget)
        self.coffee.setObjectName(_fromUtf8("coffee"))
        self.verticalLayout.addWidget(self.coffee)
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout.addWidget(self.label_8)
        self.notes = QtGui.QTextEdit(self.centralwidget)
        self.notes.setObjectName(_fromUtf8("notes"))
        self.verticalLayout.addWidget(self.notes)
        self.gridLayout.addLayout(self.verticalLayout, 0, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        pyRoast.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(pyRoast)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 19))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        pyRoast.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(pyRoast)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        pyRoast.setStatusBar(self.statusbar)

        self.retranslateUi(pyRoast)
        QtCore.QMetaObject.connectSlotsByName(pyRoast)

    def retranslateUi(self, pyRoast):
        pyRoast.setWindowTitle(_translate("pyRoast", "MainWindow", None))
        self.label_2.setText(_translate("pyRoast", "File Name:", None))
        self.bFirstCrack.setText(_translate("pyRoast", "First\n"
"Crack", None))
        self.bRollingFirstCrack.setText(_translate("pyRoast", "Rolling\n"
"First Crack", None))
        self.bSecondCrack.setText(_translate("pyRoast", "Second\n"
"Crack", None))
        self.bRollingSecondCrack.setText(_translate("pyRoast", "Rolling\n"
"Second Crack", None))
        self.bUnload.setText(_translate("pyRoast", "Unload", None))
        self.bReset.setText(_translate("pyRoast", "Reset", None))
        self.bSave.setText(_translate("pyRoast", "Save", None))
        self.bSaveAs.setText(_translate("pyRoast", "Save As", None))
        self.bLoadProfile.setText(_translate("pyRoast", "Load Profile", None))
        self.bQuit.setText(_translate("pyRoast", "Quit", None))
        self.cAutoPower.setText(_translate("pyRoast", "Auto Power", None))
        self.tPower.setText(_translate("pyRoast", "100%", None))
        self.label_3.setText(_translate("pyRoast", "Temperature:", None))
        self.label_4.setText(_translate("pyRoast", "Max Temperature:", None))
        self.tRateOfChange.setText(_translate("pyRoast", "0.0", None))
        self.label.setText(_translate("pyRoast", "Rate of Change:", None))
        self.label_5.setText(_translate("pyRoast", "Elapsed Time:", None))
        self.tMaxTemperature.setText(_translate("pyRoast", "0.0", None))
        self.tCurrentTemperature.setText(_translate("pyRoast", "0.0", None))
        self.label_6.setText(_translate("pyRoast", "Target:", None))
        self.CSLogo.setText(_translate("pyRoast", "Thanks to\n"
"CoffeeSnobs!", None))
        self.label_7.setText(_translate("pyRoast", "Coffee:", None))
        self.label_8.setText(_translate("pyRoast", "Roast Notes:", None))

from PyKDE4.kdeui import KPlotWidget, KTextBrowser, KLineEdit, KPushButton
